### PR TITLE
Added preferred replica election function for a given topic

### PR DESCRIPTION
**Pull request by wenbingshen**
I added a preferred replica election function to the theme management function,It already works right here which is friendly to the kafka-2.X version.
 This is only the first step. I will continue to improve its functions later, including integrating some interfaces of the new version of kafka.

### CODE REVIEW

**Comment by wenbingshen** [comment]
@smartloli  Good morning, smartloli. I added a preferred replica election function to the theme management of the kafka-eagle project. It already works right here. I hope you can take a look at this pr. I request to merge to the master branch.Thanks.

**Comment by smartloli** [comment]
What's the difference between this feature and the following features of `Kafka-Eagle/Topics-Hub` ?
You can look `Kafka-Eagle` url `http://localhost:8080/topic/hub` compare.

**Comment by wenbingshen** [comment]
> 此功能和的以下功能有`Kafka-Eagle/Topics-Hub`什么区别？
> 您可以看一下`Kafka-Eagle`网址`http://localhost:8080/topic/hub`比较。

Hi,smartloli.I run the master branch code now, and the access link [http://localhost:8080/topic/hub](url) reports a 403 error. I read the introduction on the official website. This function belongs to partition replica redistribution. You can look at kafka-preferred-replica-election.sh and kafka-reassign-partitions.sh in the kafka package. The difference between  scripts, which belongs to two features and different Kafka interfaces.

**Comment by wenbingshen** [comment]
@smartloli  In Kafka, it is a very cheap operation to only change the leadership level, and it has less impact on the cluster. The redistribution of partition copies will bring about the migration of disk data. In most cases, this will affect the network bandwidth of the Kafka cluster. Disk will bring pressure, I don't know if you have implemented current limiting measures for partition replicas reallocation.

**Pull request closed without merging**
